language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

services: mongodb

before_script:
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-rm xdebug.ini; fi;
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  # - yes '' | pecl install -f mongo
  # - php --ri mongo
  # - phpenv config-add etc/phpconfig.ini
  - composer self-update
  - composer install

script: vendor/bin/phpunit -c tests/
