language: php

php:
  - 5.4
  - 5.5
  - 5.6

services: mongodb

before_script:
  - phpenv config-rm xdebug.ini
  - echo "memory_limit=520M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script: vendor/bin/phpunit -c tests/
