language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

services: mongodb

before_script:
  - yes '' | pecl -q install -f mongo-stable
  # - php --ri mongo
  - phpenv config-add etc/phpconfig.ini
  - composer install

script: vendor/bin/phpunit -c tests/
