language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

services: mongodb

before_script:
  - pecl install  -f mongodb
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install

script: vendor/bin/phpunit -c tests/
