language: php

php:
  - 5.4
  - 5.5
  - 5.6

services: mongodb

before_script:
  - yes '' | pecl -q install -f mongo-stable
  - php --ri mongo
  - phpenv config-add etc/phpconfig.ini
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: phpunit -c tests/
