language: php

php:
  - 5.4
  - 5.5
  - 5.6

services: mongodb

before_script:
  - yes '' | pecl install -f mongo-stable
  - php --ri mongo
  - phpenv config-add etc/phpconfig.ini
  - curl -s http://getcomposer.org/installer | php
  - php -d memory_limit=512M composer.phar install

script: vendor/bin/phpunit -c tests/
